services:
  hapi-fhir-jpaserver-start:
    image: onc.sml.fhir:latest
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:  
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
    ports:
      - "8080:8080"
      
  hapi-fhir-postgres:
    image: postgres
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./hapi.postgress.data:/var/lib/postgresql/data 

  org.onc.ml.transformation :
    image: onc.sml.transformation:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8282/mdmi/transformation" ]
      interval: 10s
      timeout: 2s
      retries: 30
      start_period: 10s    
    mem_reservation: 4048m
    container_name: onc-mdmi
    environment:
      - JAVA_OPTS="-Xmx6048m"
      - LOGGING_LEVEL_MDMI=INFO
      - MDMI_SOURCE_FILTER_FLAG=true
    network_mode: default
    ports:
      - "8282:8282"
    restart: always
